-- MySQL Script generated by MySQL Workbench
-- Sáb 10 Dez 2016 21:49:54 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema logSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logSystem` DEFAULT CHARACTER SET utf8 ;
USE `logSystem` ;

-- -----------------------------------------------------
-- Table `logSystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logSystem`.`user` (
  `us_code` INT NOT NULL,
  `us_name` VARCHAR(100) NOT NULL,
  `us_email` VARCHAR(100) NOT NULL,
  `us_sex` VARCHAR(1) NOT NULL,
  `us_date` DATE NOT NULL,
  `us_time` TIME NOT NULL,
  `us_ip` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`us_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logSystem`.`password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logSystem`.`password` (
  `user_us_code` INT NOT NULL,
  `us_password` VARCHAR(50) NOT NULL,
  INDEX `fk_password_user_idx` (`user_us_code` ASC),
  PRIMARY KEY (`user_us_code`),
  CONSTRAINT `fk_password_user`
    FOREIGN KEY (`user_us_code`)
    REFERENCES `logSystem`.`user` (`us_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
